[package]
name = "taller-metodos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
approx = "0.4.0"
ndarray = { version = "0.15.6", features = ["approx"] }
